### ISSUE TITLE
Heads up

### ISSUE THREAD

**Issue by im50urce** [kozennnn/simple-skyblock#1]
For the users who wanne use this the table is never made in your MySQL I would suggest make your own or look for a other plugin

**Comment by mathishouis** [comment]
Hi! I'm sorry for that, I've never really noticed that the sql file wasn't available in the release. It's fixed now with the release v0.2-ALPHA, a file named "database.sql" has been added to the archive. [The release is available here](https://github.com/kozennnn/simple-skyblock/releases/tag/v0.2-ALPHA). Thanks for the issue!

**Comment by im50urce** [comment]
No worries as I said it’s just a heads up and I was working after that message on the fix so I could add it here but thanks for the fast response 👍
