### ISSUE TITLE
is create cant add island on 1.19.4 Paper

### ISSUE THREAD

**Issue by Haeherfeder** [kozennnn/simple-skyblock#15]
the island.schmatics file cant be loaded, worked for me, after i replaced it with one created by worledit

(if you need the log, i can send them, but these are from the code, which is in the pull request)

**Comment by mathishouis** [comment]
I'll try to fix this issue this evening 😸 Can you send me the schematic you created with worldedit please?

**Comment by Haeherfeder** [comment]
sure, but is a really basic island (2 3*3 layers stone, one layer grass, a tree, a chest with bonemeal, lava and ice, and bread iirc), only that i can try it

i cant append on github, should i send it per mail, upload it in my repo or discord?

**Comment by mathishouis** [comment]
You can send me the file on discord at @kozennnn

**Comment by Haeherfeder** [comment]
you got a friend request
