### ISSUE TITLE
No More Changes?

### ISSUE THREAD

**Issue by DevSnx** [kozennnn/simple-skyblock#2]

**Comment by mathishouis** [comment]
Hi, i'm probably going to work on the plugin when i will have more time because for the moment i have school. So there should be new updates soon 😄 !

**Comment by DevSnx** [comment]
i would look to Update you repo with permissions with my codes? You accept Pule requests?

**Comment by mathishouis** [comment]
Yes absolutly!

**Comment by DevSnx** [comment]
I have made 2 Pull Requests :)

**Comment by mathishouis** [comment]
I'm looking them 😄

**Comment by mathishouis** [comment]
Merged! Thanks for the pull request 😛

**Comment by DevSnx** [comment]
Can add me, so i can push without pullrequests? :-)

**Comment by mathishouis** [comment]
I'm sorry but i prefer reviewing the pull requests before merging them 😄
