### ISSUE TITLE
Merge the 3 invite commands

### ISSUE THREAD

**Issue by mathishouis** [kozennnn/simple-skyblock#8]
It can be better to merge the `/island accept`, `/island deny` and `/island invite %player%` commands into one. For example we can replace the `/island accept` command by `/island invite accept`, the _/island deny_ command by `/island invite deny` and the `/island invite %player%` command by `/island invite add %player%`.

**Comment by TheExotik** [comment]
this kinda useless i think, i mean why all this work to just make a new command, to execute the same thing?

**Comment by mathishouis** [comment]
I think it could make the code cleaner, instead of having 3 different commands to manage the invitations, we can have now just one command for it. And it shouldn't be a lot of work like we just have to take the accept and deny command, merge it into the invite command and check the parameters to see if the user want to execute the deny, accept or invite option. 😸
